service: node-api-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # or any region you prefer
  environment:
    CLIENT_URL: https://yourfrontend.com
    MONGO_URI: your-mongodb-uri

functions:
  app:
    handler: src/lambda.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .git/**
    - .env